### PR TITLE
Tycho build

### PR DESCRIPTION
**Pull request by cawal**
Hi! I use Maven to manage the dependencies and build my projects. Thus, I created a branch in my fork and added a Tycho build config for the openapi-metamodel project. 

Until now, it seems working for my project with no build problems. It not removes the need for Eclipse in the transformation of the Ecore model to the Java classes, but in can be used to compile these classes  (`mvn compile`) and create the JAR package standalone and install it on the local Maven repository (`mvn install`). Also, I did'nt removed the Gson jar from the branch, but I think it may be later externalized to the POM files.

I hope this may have some value for you too.

### CODE REVIEW

**Comment by hamzaed** [comment]
Thank you for your contribution. In deed, this will facilitate the integration of the OpenAPI metamodel in standalone applications. I'll review your pull request as soon as I can.

**Comment by hamzaed** [comment]
Hi @cawal 
Your pull request is located in the branch  [cawal-tycho-buildl](https://github.com/opendata-for-all/openapi-metamodel/tree/cawal-tycho-buildl).

I'm getting the following errors when I try to build the project using maven:

`[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: edu.uoc.som.openapi 2.0.0.qualifier
[ERROR]   Missing requirement: edu.uoc.som.openapi 2.0.0.qualifier requires 'bundle org.eclipse.core.runtime 0.0.0' but it could not be found
`
It seems that the eclipse repository cannot be reached to resolve this dependency. Would you check again if you could build the project.

Thanks,

Hamza

**Comment by jachinte** [comment]
Hi @hamzaed,
I'm sorry to hijack the conversation. I'm using Gradle and it would be great to remove the local JAR files. I built the branch you mention with no problems.

**Comment by hamzaed** [comment]
Hi @jachinte,
I had to add a target definition to be able to build but now it works. I added an issue regarding the local JAR files. We'll work on it ASAP.

**Comment by jachinte** [comment]
Thank you, @hamzaed!
This is great. I meant, it would be great to just depend on the maven artifacts so that I can remove the local Jar files from my build (`edu.uoc.som.openapi-1.0.2.201804111106.jar` and  `edu.uoc.som.openapi.io-1.0.3.201804111106.jar`).

**Pull request merged**
